https://dbdiagram.io/d/Canine Database 654a77be7d8bbd6465b0ff2f
https://dbdiagram.io/d/Canine_Database-654a77be7d8bbd6465b0ff2f

INSERT INTO Dogs
VALUES ('Canis lupus familiari','A domesticated descendant of the wolf. Also called the domestic dog, it is derived from extinct Pleistocene wolves, and the modern wolf is the dogs nearest living relative');

INSERT INTO herding (herding_name, description)
VALUES ('Australian Cattle Dog','The compact but muscular Australian Cattle Dog, also called Blue or Red Heeler or Queensland Heeler, is related to Australis famous wild dog, the Dingo. These resilient herders are intelligent enough to routinely outsmart their owners. Standing between 17 to 20 inches at the shoulder, the Australian Cattle Dog is a sturdy, hard muscled herder of strength and agility. The ACD is born with a white coat that turns either blue gray or red. Both coat colors may feature distinctive mottling or speckling patterns. ACDs have immense work drive and excel at controlling and, of course, moving livestock. Their boundless energy and supple gait make them excellent running partners. ACDs are true blue loyal, famously smart, tenacious, ever alert, and may be wary of strangers. If an ACD ist challenged, it easily becomes bored and may get into mischief. It is recommended that ACD owners participate with these versatile dogs in some work, sport, or regular exercise to keep them mentally and physically fit.
Standing between 17 to 20 inches at the shoulder, the Australian Cattle Dog is a sturdy, hard muscled herder of strength and agility. The ACD is born with a white coat that turns blue gray or red. Both coat varieties feature distinctive mottling or specking patterns. ACDs have immense work drive and excel at hunting, chasing, and, of course, moving livestock. Their boundless energy and supple gait make them excellent running partners.   ACDs are true blue loyal, famously smart, ever alert, and wary of strangers. If an ACD isnt challenged, he easily becomes bored and gets into mischief. It is recommended that ACD owners participate with their dog in some work, sport, or regular exercise to keep him mentally and physically fit');

INSERT INTO herding (herding_name, description)
VALUES ('Australian Shepherd','The Australian Shepherd, a lean, tough ranch dog: a European breed perfected in California by way of Australia. Fixtures on the rodeo circuit, they are closely associated with the cowboy life. The Australian Shepherd, the cowboys herding dog of choice, is a medium sized worker with a keen, penetrating gaze in the eye. Aussie coats offer different looks, including merle (a mottled pattern with contrasting shades of blue or red). In all ways, theyre the picture of rugged and agile movers of stock. Aussies exhibit an irresistible impulse to herd, anything: birds, dogs, kids. This strong work drive can make Aussies too much dog for a sedentary pet owner. Aussies are remarkably intelligent, quite capable of hoodwinking an unsuspecting novice owner. In short, this ist the pet for everyone. But if youre looking for a brainy, tireless, and trainable partner for work or sport, your search might end here.');

INSERT INTO hound (hound_name, description)
VALUES ('Afghan Hound', 'Among the most eye catching of all dog breeds, the Afghan Hound is an aloof and dignified aristocrat of sublime beauty. Despite his regal appearance, the Afghan can exhibit an endearing streak of silliness and a profound loyalty. Since ancient times, Afghan Hounds have been famous for their elegant beauty. But the thick, silky, flowing coat that is the breeds crowning glory isnt just for show, it served as protection from the harsh climate in mountainous regions where Afghans originally earned their keep. Beneath the Afghans glamorous exterior is a powerful, agile hound standing as high as 27 inches at the shoulder, built for a long days hunt. Their huge paw pads acted as shock absorbers on their homelands punishing terrain.');

INSERT INTO hound (hound_name, description)
VALUES ('American English Coonhound', 'These sleek and racy, lean but muscular hounds work dusk to dawn in pursuit of the wily raccoon. The sight of the American English Coonhound tearing through the moonlit woods, all sinew and determination, bawling their lusty night music, is coon hunter heaven. Standing as high as 26 inches at the shoulder, American English Coonhounds are deep chested, sweet faced athletes beloved by sportsmen for their speed and endurance. Stretched tightly across the athletic frame is a medium length coat of various patterns, some with ticking. The head is broad with a domed skull, with soft, low hung ears and dark brown eyes that glow with warmth and kindness. American English Coonhounds are mellow when off duty but tenacious and stubborn in pursuit of their ring tailed prey. Their work drive and energy, the patience it takes to train them for things other than coon hunting, and their loud, ringing bark can make the breed a bad fit as house pets for novice owners. Some passionate fans of American English Coonhounds feel that without a sporting outlet for this breeds houndy virtues, youre simply wasting a good dog.');

INSERT INTO non_sporting (non_sporting_name, description)
VALUES ('American Eskimo Dog','The American Eskimo Dog combines striking good looks with a quick and clever mind in a total brains and beauty package. Neither shy nor aggressive, Eskies are always alert and friendly, though a bit conservative when making new friends. The American Eskimo Dog comes in three sizes: standard, miniature, and toy standing as tall as 19 inches at the shoulder or as short as 9 inches. Distinctive traits include a dense, sparkling white coat with a lion like ruff around the chest and shoulders; a smiling face, with black nose, lips, and eye rims that convey a keen, intelligent expression; and a plumed tail carried over the back. Some Eskies have markings with the delicious color name. They move with a bold and agile gait. Eskies are social animals and can develop problem behaviors when neglected or undertrained, they insist on being part of family life. Among the most trainable of breeds, the clever, kid friendly Eskie practically invented the phraseeager to please.');

INSERT INTO non_sporting (non_sporting_name, description)
VALUES ('Bichon Fris','The small but sturdy and resilient Bichon Frise stands among the worlds great personality dogs.Since antiquity, these irresistible canine comedians have relied on charm, beauty, and intelligence to weather historys ups and downs. A good size Bichon will stand a shade under a foot tall at the shoulder. The breeds glory is a white hypoallergenic coat, plush and velvety to the touch, featuring rounded head hair that sets off the large, dark eyes and black leathers of the nose and lips. Bichons are adaptable companions who get on well with other dogs and children. Alert and curious, Bichons make nice little watchdogs but they are lovers, not fighters, and operate under the assumption that there are no strangers, just friends they havent met yet. Their confidence and size make them ideal city dogs. Bichons train nicely and enjoy performing for their loved ones. Finally, theres the happy go lucky Bichon personality that draws smiles and hugs wherever they go');

INSERT INTO sporting (sporting_name, description)
VALUES ('American Water Spaniel','The American Water Spaniel, native to the lake country of the upper Midwest, is an upbeat, outdoorsy athlete who loves to hunt and swim. They are known to be happy, eager, and charming, though aloof with strangers and a bit stubborn. American Water Spaniels are muscular midsize gundogs, not flashy in looks or performance, and recognizable by a luscious brown coat that is either tightly curled or wavy. Bred to work the icy waters and marshy banks of the Great Lakes region, these spaniels are ideally outfitted for the job: The coat is dense and waterproof, the feet are thickly padded, the toes are webbed, and the body is small enough for the dog to hop in and out of a skiff without rocking the boat. The breeds admirers describe a merry, intelligent, and versatile spaniel suited to a variety of dog sports. As hunters, they combine the working traits of spaniels and retrievers. The key to the American Water Spaniels happiness is activity, especially alongside their adored human. An underemployed dog can be barky and destructive');

INSERT INTO sporting (sporting_name, description)
VALUES ('Barbet', 'An archetypic water dog of France, the Barbet is a rustic breed of medium size and balanced proportions who appears in artwork as early as the 16th century. In profile, the Barbet is slightly rectangular with a substantial head and long, sweeping tail. He has a long, dense covering of curly hair and a distinctive beard. An agile athlete, the Barbet has been used primarily to locate, flush, and retrieve birds. He has a cheerful disposition and is very social and loyal.
The defining characteristic of this rustic, medium sized bird dog is the dense curly coat that covers him from the top of his large, broad head to the tip of his curving tail. The coat comes in shades of black, gray, brown, or fawn, sometimes with white markings. The breeds delightfully shaggy coat and amiable nature creates the impression of a Muppet come to life, but the Barbet is a strong, solidly built dog bred for centuries to be a keen hunter and tireless swimmer. Barbets are very intelligent and learn new things quickly. They have a calm nature and are easy to live with as long as their exercise needs are being met.');

INSERT INTO terrier (terrier_name, description)
VALUES ('Airedale Terrier', 'His size, strength, and unflagging spirit have earned the Airedale Terrier a nickname. The Airedale stands among the worlds most versatile dog breeds and has distinguished himself as hunter, athlete, and companion.
The Airedale Terrier is the largest of all terrier breeds. Males stand about 23 inches at the shoulder, females a little less. The dense, wiry coat is tan with black markings. Long, muscular legs give Airedales a regal lift in their bearing, and the long head with its sporty beard and mustache, dark eyes, and neatly folded ears conveys a keen intelligence. Airedales are the very picture of an alert and willing terrier only bigger. And, like his smaller cousins in the terrier family, he can be bold, determined, and stubborn. Airedales are docile and patient with kids but wont back down when protecting hearth and home. Thanks to their famous do it all attitude, Airedales excel in all kinds of sports and family activities.');

INSERT INTO terrier (terrier_name, description)
VALUES ('American Hairless Terrier', 'The American Hairless Terrier, a Louisiana native, is a smart, inquisitive, and playful dog that comes in hairless and coated varieties. He is a fine choice for allergy sufferers who want a dog with true terrier grit and courage.
The American Hairless Terrier stands between 12 to 16 inches at the shoulder, and comes in both coated and hairless varieties. The hairless variety might have eyebrows and whiskers, while the coated has a short, shiny coat. The skin of the hairless is smooth and warm to the touch. The broad, wedge shaped head is a hallmark of both varieties. Erect, V shaped ears frame the round, expressive eyes that gleam with curiosity.
 The American Hairless moves with jaunty pep in his step that announces real terrier attitude. The hairless variety is as hypoallergenic as a dog can get. Hairlessness, though, presents its own challenges. Sunburn is a concern, and cold weather requires special precautions. This breed is protective of their humans and make alert watchdogs.');

INSERT INTO toy (toy_name, description)
VALUES ('Affenpinscher', 'Loyal, curious, and famously amusing, this almost human toy dog is fearless out of all proportion to his size. As with all great comedians, its the Affenpinschers apparent seriousness of purpose that makes his antics all the more amusing.

The Affens apish look has been described many ways. Theyve been called monkey dogs and ape terriers. The French say diablotin moustachu (mustached little devil), and Star Wars fans argue whether they look more like Wookies or Ewoks.     Standing less than a foot tall, these sturdy terrier like dogs approach life with great confidence. This isnt a breed you train, a professional dog handler tells us, Hes like a human. You befriend him. The dense, harsh coat is described as neat but shaggy and comes in several colors; the gait is light and confident. They can be willful and domineering, but mostly Affens are loyal, affectionate, and always entertaining. Affen people say they love being owned by their little monkey dogs.');

INSERT INTO toy (toy_name, description)
VALUES ('Biewer Terrier','The Biewer Terrier is an elegant, longhaired, tri colored toy terrier whose only purpose in life is to love and be loved. They maintain a charming, whimsical attitude well into adulthood. Carrying around a toy or two is not surprising.

The Biewer Terrier is a very dedicated, loyal family member and friendly with strangers. A large percentage of the Biewer Terriers are happy go lucky dogs, smiling when asked if they are happy. In spite of its small stature, the Biewer is a very hearty, athletic dog and an excellent hunter of vermin. They are lighthearted, have a childlike attitude and like to carry toys in their mouths. He is quick to alert you to company, but is not a constant barker. How do you pronounce Biewer Terrier? Beaver, exactly like out little dam building friends.');

INSERT INTO working (working_name, description)
VALUES ('Akita', 'The Akita is a muscular, double coated dog of ancient Japanese lineage famous for their dignity, courage, and loyalty. In their native land, theyre venerated as family protectors and symbols of good health, happiness, and long life.

Akitas are burly, heavy boned spitz type dogs of imposing stature. Standing 24 to 28 inches at the shoulder, Akitas have a dense coat that comes in several colors, including white. The head is broad and massive, and is balanced in the rear by a full, curled over tail. The erect ears and dark, shining eyes contribute to an expression of alertness, a hallmark of the breed. Akitas are quiet, fastidious dogs. Wary of strangers and often intolerant of other animals, Akitas will gladly share their silly, affectionate side with family and friends. They thrive on human companionship. The large, independent thinking Akita is hardwired for protecting those they love. They must be well socialized from birth with people and other dogs.');

INSERT INTO working (working_name, description)
VALUES ('Alaskan Malamute', 'An immensely strong, heavy duty worker of spitz type, the Alaskan Malamute is an affectionate, loyal, and playful but dignified dog recognizable by his well furred plumed tail carried over the back, erect ears, and substantial bone. The Alaskan Malamute stands 23 to 25 inches at the shoulder and weighs 75 to 85 pounds. Everything about Mals suggests their origin as an arctic sled dog: The heavy bone, deep chest, powerful shoulders, and dense, weatherproof coat all scream, I work hard for a living! But their almond shaped brown eyes have an affectionate sparkle, suggesting Mals enjoy snuggling with their humans when the workday is done. Mals are pack animals. And in your family pack, the leader must be you. If a Mal doesnt respect you, he will wind up owning you instead of the other way around. Firm but loving training should begin in early puppyhood. That said, a well behaved Mal is a joy to be with playful, gentle, friendly, and great with kids.');